config/routes.rb
Rails.application.routes.draw do
  root to: "landing_page#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :fundraisers
  resources :donations

  get '/stripe_testing', to: 'stripe_testing#index', as: 'stripe_testing'
  get '/landing_page', to: 'landing_page#index'
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :fundraiser
end

app/models/fundraiser.rb
class Fundraiser < ActiveRecord::Base
  has_many :donations
  has_many :users, :through => :donations
  belongs_to :user
  has_attached_file :picture, :styles => { :medium => "300x300>", :checkout => "128x128>", :list => "100x100" }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def self.has_fundraiser
    return (current_user && current_user.fundraiser)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :donations
  has_many :fundraisers, :through => :donations
  has_one :fundraiser

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @name = "Bill"
  end

  def create
    # Set secret key: remember to change this to live secret key in production
    Stripe.api_key = "sk_test_gIgy2ECRkPETPxugi8IuHm1X"

    # Get the credit card details submitted by the form
    token = params[:stripe_token]
    amount = params[:stripe_amount].to_i * 100

    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => amount,
        :currency => "usd",
        :source => token,
        :description => "Example charge"
      )
      flash[:notice] = "Payment submitted!"
      redirect_to :back
    rescue Stripe::CardError => e
      # The card has been declined
    end
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def new
    @name = "Bill"
  end

  def create
    # Set secret key: remember to change this to live secret key in production
    Stripe.api_key = "sk_test_gIgy2ECRkPETPxugi8IuHm1X"

    # Get the credit card details submitted by the form
    token = params[:stripe_token]
    amount = (params[:stripe_amount].to_f * 100).round
    fundraiser_id = params[:fundraiser_id]

    fundraiser = Fundraiser.find(fundraiser_id)
    donation = Donation.create(user_id: current_user, amount: amount, user_id: current_user.id)

    fundraiser.donations.push(donation);

    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      # charge = Stripe::Charge.create(
      charge = Stripe::Charge.create(
        :amount => amount,
        :currency => "usd",
        :source => token,
        :description => "Example charge"
      )
      flash[:notice] = "Payment submitted!"
      redirect_to :back
    rescue Stripe::CardError => e
      # The card has been declined
    end
  end
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  before_action :authenticate_user!
  before_filter has_fundraiser: false, :except => [:show, :index, :edit, :update, :destroy]

  def index
    @fundraisers = Fundraiser.all
  end

  def new
    @fundraiser = Fundraiser.new
  end

  def create
    @fundraiser = Fundraiser.new(fundraiser_params)
    @fundraiser.update(user_id: current_user.id)
    if @fundraiser.save
      flash[:notice] = "Your hipster has been added despite his protests about this being lame"
      redirect_to fundraisers_path
    else
      flash[:notice] = "Your hipster is too cool for this. Give him a stern talking-to and try again"
      render :new
    end
  end

  def show
    @fundraiser = Fundraiser.find(params[:id])
    @total = 0.0
    @fundraiser.donations.each do |donation|
      @total += donation.amount / 100
    end

  end

  def edit
    @fundraiser = Fundraiser.find(params[:id])
  end

  def update
    fundraiser = Fundraiser.find(params[:id])
    fundraiser.update(fundraiser_params)
    redirect_to :back
  end

  def destroy
    fundraiser = Fundraiser.find(params[:id])
    fundraiser.destroy
    redirect_to fundraisers_path
  end

  private

    def fundraiser_params
      params.require(:fundraiser).permit(:name, :description, :picture)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipients = Recipient.all
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
    @recipient = params.find(:id)
  end

  def update
    recipient = params.find(:id)
    recipient.update(recipient_params)
    redirect_to :back
  end

  def destroy
    recipient = params.find(:id)
    recipient.destroy
    redirect_to :back
  end

  private

    def recipient_params
      params.require(:recipient).permit(:name, :description)
    end
end

app/controllers/stripe_testing_controller.rb
class StripeTestingController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :admin
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :admin
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<!-- http://stackoverflow.com/questions/20049865/stripe-checkout-with-custom-integration-in-rails -->
<%= form_tag charges_path, id: 'chargeform' do %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <div class="input-group">
    <span class="input-group-addon">$</span>
    <%= text_field_tag :stripe_amount, nil, class:"form-control", id: "custom_amount" %>
  </div>
  <%= hidden_field_tag 'stripe_token', "" %>
  <%= hidden_field_tag 'stripe_email', "" %>
  <button id="customButton" class="btn btn-large btn-primary">Donate!</button>

  <script>
    var handler = StripeCheckout.configure({
      key: 'pk_test_yckTsrSU974a9Xb6dE4jAWhM',
      image: '/assets/tie.png',
      token: function(token) {
        $("#stripe_token").val(token.id);
        $("#stripe_email").val(token.email);
        $("#chargeform").submit();
      }
    });

    $('#customButton').on('click', function(e) {
      var amount = $("#custom_amount").val();
      // Open Checkout with further options
      handler.open({
        name: 'Donating $' + amount,
        description: 'Your donation changes lives.',
        amount: amount * 100
      });
      e.preventDefault();
    });
  </script>
<% end %>

app/views/charges/success.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_yckTsrSU974a9Xb6dE4jAWhM"
          data-description=<%= @name %>
          data-amount="500"></script>
<% end %>

app/views/donations/_form.html.erb
<!-- http://stackoverflow.com/questions/20049865/stripe-checkout-with-custom-integration-in-rails -->
<%= form_tag donations_path, id: 'chargeform' do %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <div class="input-group">
    <span class="input-group-addon">$</span>
    <%= text_field_tag :stripe_amount, nil, class:"form-control", id: "custom_amount" %>
  </div>
  <%= hidden_field_tag 'stripe_token', "" %>
  <%= hidden_field_tag 'stripe_email', "" %>
  <%= hidden_field_tag 'fundraiser_id', @fundraiser.id %>
  <button id="customButton" class="btn btn-large btn-primary">Donate!</button>

  <script>


    $('#customButton').on('click', function(e) {
      e.preventDefault();
      var handler = StripeCheckout.configure({
        key: 'pk_test_yckTsrSU974a9Xb6dE4jAWhM',
        image: '/assets/tie.png',
        token: function(token) {
          $("#stripe_token").val(token.id);
          $("#stripe_email").val(token.email);
          $("#chargeform").submit();
        }
      });

      var amount = $("#custom_amount").val();
      // Open Checkout with further options
      handler.open({
        name: 'Donating $' + amount,
        description: 'Your donation changes lives.',
        amount: amount * 100
      });
    });
  </script>
<% end %>

app/views/donations/new.html.erb
Success!

app/views/donations/success.html.erb
<%= form_tag donations_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_yckTsrSU974a9Xb6dE4jAWhM"
          data-description=<%= @name %>
          data-amount="500"></script>
<% end %>

app/views/fundraisers/_form.html.erb
<%= bootstrap_form_for @fundraiser do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.file_field :picture %>
  <%= f.submit "Submit Changes" %>
<% end %>

app/views/fundraisers/edit.js.erb
$('.edit_hipster').hide().after('<%= j render ("form") %>');

app/views/fundraisers/index.html.erb
<h1>Hipstarter</h1>

<% if @fundraisers.any? %>
  <ul>
  <% @fundraisers.each do |fundraiser| %>
    <li><strong><%= link_to fundraiser.name, fundraiser_path(fundraiser) %></strong></li>

  <% end %>
  </ul>
  <% else %>
  <p>There are no hipsters added yet! Head to Hawthorne to find more</p>
<% end %>

<% if current_user.admin || current_user.fundraiser == nil %>
  <%= link_to "Add a Hipster", new_fundraiser_path, class: "add_hipster", remote: true %>
<% end %>

app/views/fundraisers/new.js.erb
$(".add_hipster").hide().after("<%= j render ('form') %>");

app/views/fundraisers/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><i><%= @fundraiser.name %></i></h1>
    <% if @fundraiser.picture.present? %>
      <%= image_tag @fundraiser.picture(:medium) %>
    <% end %>
    <p>This hipster's total donations: $<%= @total %></p>

    <p><%= @fundraiser.description %></p>
    <%= render "donations/form" %>

    <% if current_user.admin || current_user.fundraiser == @fundraiser %>
      <%= link_to "Edit Hipster",  edit_fundraiser_path(@fundraiser), class: "edit_hipster", remote: true%>
      <br>
      <%= link_to "Delete Hipster", fundraiser_path(@fundraiser), :data => {method: 'delete'} %>
    <% end %>
  </div>
</div>

app/views/landing_page/index.html.erb
<style>
  .navbar {
    display: none;
  }
</style>

<div class="overlay">
</div>

<div class="landing-page-wrapper absolutely-centered">
  <h1 class="page-header mega">HIPSTARTER</h1>

  <p class="lead">
    Hipstarter connects generous 'givers' with hipsters low on funds. Because every hipster deserves a craft brew.
  </p>

  <%= link_to "Adopt a Hipster", fundraisers_path, class:"buttonify large" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipstarter</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <% if flash[:notice] %>
    <div class="flash-wrapper">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <nav class="navbar navbar-default navbar-fixed-bottom">

    <ul class="nav navbar-nav">
      <%= link_to image_tag("/images/camera_icon.png", class: "camera_icon"), root_path %>


      <% if user_signed_in? %>
        <li class="navbar-right">
          <span>
              You are logged in as <i><%= current_user.email %></i>! |
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </span>
        </li>
      <% else %>
        <li class="navbar-right"><%= link_to "Sign In", new_user_session_path %></li>
        <li class="navbar-right"><%= link_to "Signup",  new_user_registration_path %></li>
      <% end %>

    </ul>
    </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/recipients/_form.html.erb
<%= form_for @recipient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit "Submit Changes" %>
<% end %>

app/views/stripe_testing/index.html.erb
<div class="absolutely-centered">
  Click to donate
</div>

<form action="" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_yckTsrSU974a9Xb6dE4jAWhM"
    data-amount="2000"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-image="/128x128.png">
  </script>
</form>